window.PRODUCTS = [
  {id:"0001",name:"Louis Vuitton Odyssee Monogram Bag",category:"Bags",subcategory:"Shoulder Bags",price:365,currency:"USD",sizes:"Standard",colors:"Brown",material:"Monogram finish",description:"Elegant monogram shoulder bag with a refined everyday design.",dimensions:"27 × 17 × 12 cm",badge:"New",featured:true,images:["images/0001.jpg","images/0002.jpg","images/0003.jpg","images/0004.jpg"]},
  {id:"0002",name:"Christian Dior Lady Dior Handbag",category:"Bags",subcategory:"Handbags",price:335,currency:"USD",sizes:"Standard",colors:"Pale Gold",material:"Quilted finish",description:"Elegant structured handbag with refined detailing and hanging letter charms.",dimensions:"20 × 16 × 8 cm",badge:"Trending",featured:true,images:["images/0005.jpg", "images/0006.jpg", "images/0007.jpg", "images/0008.jpg"]},
  {id:"0003",name:"Chanel Raffia Shopping Tote",category:"Bags",subcategory:"Tote Bags",price:345,currency:"USD",sizes:"Standard",colors:"Natural / Black",material:"Raffia / quilted finish",description:"Raffia shopping tote with a polished black front pocket and statement hardware.",dimensions:"34 × 17 × 12.5 cm",badge:"Trending",featured:false,images:["images/0009.jpg", "images/0010.jpg", "images/0011.jpg", "images/0012.jpg"]},
  {id:"0004",name:"Louis Vuitton Alma BB Bag",category:"Bags",subcategory:"Handbags",price:335,currency:"USD",sizes:"BB",colors:"Damier Ebene / Dark Brown",material:"Canvas finish",description:"Classic structured silhouette with dark brown trim and polished gold-tone details.",dimensions:"23.5 × 17.5 × 11.5 cm",badge:"Popular",featured:true,images:["images/0013.jpg", "images/0014.jpg", "images/0015.jpg", "images/0016.jpg"]},
  {id:"0005",name:"Louis Vuitton Neverfull MM in Monogram Empreinte Leather",category:"Bags",subcategory:"Tote Bags",price:355,currency:"USD",sizes:"MM",colors:"Burgundy",material:"Empreinte leather finish",description:"Spacious tote with an elegant embossed finish and polished hardware.",dimensions:"31 × 28 × 14 cm",badge:"New",featured:true,images:["images/0017.jpg", "images/0018.jpg", "images/0019.jpg", "images/0020.jpg"]},
  {id:"0006",name:"Chanel Caoutchouc CC High Boots",category:"Shoes",subcategory:"High Boots",price:275,currency:"USD",sizes:"Multiple Sizes",colors:"Black",material:"Rubber finish",description:"Statement high boots with a sleek finish and distinctive detailing.",dimensions:"Standard",badge:"New",featured:false,images:["images/0021.jpg", "images/0022.jpg", "images/0023.jpg", "images/0024.jpg"]},
  {id:"0007",name:"Chanel Suede Calfskin CC Mules",category:"Shoes",subcategory:"Mules",price:235,currency:"USD",sizes:"Multiple Sizes",colors:"Dark Beige / Brown",material:"Suede finish",description:"Elegant mules with a refined finish and distinctive signature detailing.",dimensions:"Standard",badge:"New",featured:true,images:["images/0025.jpg", "images/0026.jpg", "images/0027.jpg", "images/0028.jpg"]},
  {id:"0008",name:"Chanel Short Biker Boots",category:"Shoes",subcategory:"Short Biker Boots",price:265,currency:"USD",sizes:"Multiple Sizes",colors:"Black",material:"Leather-style finish",description:"Short biker boots featuring a polished buckle detail and confident everyday styling.",dimensions:"Standard",badge:"Featured",featured:false,images:["images/0029.jpg", "images/0030.jpg", "images/0031.jpg", "images/0032.jpg"]},
  {id:"0009",name:"Saint Laurent Le Loafer",category:"Shoes",subcategory:"Loafers",price:255,currency:"USD",sizes:"Multiple Sizes",colors:"Black",material:"Leather-style finish",description:"Classic black loafer with a clean and sophisticated silhouette.",dimensions:"Standard",badge:"Popular",featured:false,images:["images/0033.jpg", "images/0034.jpg", "images/0035.jpg", "images/0036.jpg"]},
  {id:"0010",name:"Gucci x adidas Gazelle GG Monogram Sneakers",category:"Shoes",subcategory:"Sneakers",price:235,currency:"USD",sizes:"Multiple Sizes",colors:"Monogram",material:"Textile / suede-style finish",description:"Statement sneaker with a sporty silhouette and distinctive patterned finish.",dimensions:"Standard",badge:"Trending",featured:false,images:["images/0037.jpg", "images/0038.jpg", "images/0039.jpg", "images/0040.jpg"]},
  {id:"0011",name:"Louis Vuitton Speedy Soft 30 Dark Monogram Bag",category:"Bags",subcategory:"Handbags",price:375,currency:"USD",sizes:"30",colors:"Dark Monogram",material:"Soft structured finish",description:"Soft structured handbag featuring a sophisticated dark patterned finish.",dimensions:"30 cm",badge:"Featured",featured:true,images:["images/0041.jpg", "images/0042.jpg", "images/0043.jpg", "images/0044.jpg"]},
  {id:"0012",name:"Christian Dior Dusty Ivory Macrocannage Calfskin Dior Groove Bag",category:"Bags",subcategory:"Shoulder Bags",price:345,currency:"USD",sizes:"Standard",colors:"Dusty Ivory",material:"Calfskin-style finish",description:"Refined shoulder bag in a soft ivory tone with a textured finish.",dimensions:"25 × 19 × 6 cm",badge:"New",featured:true,images:["images/0045.jpg", "images/0046.jpg", "images/0047.jpg", "images/0048.jpg"]},
  {id:"0013",name:"Hermes Birkin Bag",category:"Bags",subcategory:"Structured Bags",price:525,currency:"USD",sizes:"30 cm",colors:"Black",material:"Leather-style finish",description:"Elegant structured black bag with polished gold-tone hardware.",dimensions:"30 cm",badge:"Featured",featured:true,images:["images/0049.jpg", "images/0050.jpg", "images/0051.jpg", "images/0052.jpg"]},
  {id:"0014",name:"Louis Vuitton Speedy Bandouliere 20 Damier Ebene Canvas Bag",category:"Bags",subcategory:"Crossbody Bags",price:335,currency:"USD",sizes:"20",colors:"Damier Ebene",material:"Canvas finish",description:"Compact crossbody silhouette in a classic patterned finish.",dimensions:"20.5 × 13.5 × 12 cm",badge:"Featured",featured:true,images:["images/0053.jpg", "images/0054.jpg", "images/0055.jpg", "images/0056.jpg"]},
  {id:"0015",name:"Goyard Goyardine Sac Cap Vert Black Crossbody Bag",category:"Bags",subcategory:"Crossbody Bags",price:265,currency:"USD",sizes:"Standard",colors:"Black",material:"Patterned canvas-style finish",description:"Compact black crossbody bag with a practical everyday silhouette.",dimensions:"Standard",badge:"New",featured:false,images:["images/0057.jpg", "images/0058.jpg", "images/0059.jpg", "images/0060.jpg"]},
  ];
window.STORE={name:"Elite Bags",email:"luxuriouselitebags@gmail.com",whatsapp:"+1 208-903-4508",whatsappLink:"https://wa.me/12089034508",tiktok:"https://www.tiktok.com/@elite.bagss",address:"Guang Zhou Shi, Guang Dong Sheng, China",quality:"Master Quality",shipping:"Free Worldwide Shipping",delivery:"9–13 Working Days",currency:"USD"};
window.CATEGORIES=["Bags","Shoes","Watches","Accessories"];
